// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAluC4gE16FOiT1W1_CQqdx7MV1XBu-SYc',
//     appId: '1:2509166822:web:f2075e9cc44d69205a4327',
//     messagingSenderId: '2509166822',
//     projectId: 'weather-1d393',
//     authDomain: 'weather-1d393.firebaseapp.com',
//     storageBucket: 'weather-1d393.appspot.com',
//     measurementId: 'G-9EY6956TCR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBmE7adSX_N7OckS8lskYhiUBE3AlGHZYc',
//     appId: '1:2509166822:android:4e62a87f294368175a4327',
//     messagingSenderId: '2509166822',
//     projectId: 'weather-1d393',
//     storageBucket: 'weather-1d393.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB2Wb3THSSWmQcjrv87ypfKPLDugL9qsaw',
//     appId: '1:2509166822:ios:dc2ec49707ed90895a4327',
//     messagingSenderId: '2509166822',
//     projectId: 'weather-1d393',
//     storageBucket: 'weather-1d393.appspot.com',
//     iosBundleId: 'com.example.chatApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB2Wb3THSSWmQcjrv87ypfKPLDugL9qsaw',
//     appId: '1:2509166822:ios:0121760b936c1ce65a4327',
//     messagingSenderId: '2509166822',
//     projectId: 'weather-1d393',
//     storageBucket: 'weather-1d393.appspot.com',
//     iosBundleId: 'com.example.chatApp.RunnerTests',
//   );
// }
